version: '3.9'
services:
  app:
    build: 
      context: .
    container_name: ${APP_NAME}_frontend
    tty: true
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    ports:
      - 3000:3000
volumes:
  db-store: